baseURL = 'https://theatrebuilding.com/'
languageCode = 'en-us'
title = 'theatrebuilding.com'
theme = "octaTheme"


[taxonomies]
tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
